[dns_servers]
dns.lab ansible_host=192.168.2.10

[all:vars]
ansible_user=jay
# Temp keys used to bootstrap
ansible_ssh_private_key_file=~/.ssh/id_vlab
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_python_interpreter=/usr/bin/python3
